linters:
  enable-all: true
  disable:
    # deprecated linters
    - gomnd
    - execinquery
    - exportloopref

    - gomodguard # flag go module dependencies based on allow/blocklist
    - gomoddirectives # flag go module directives

linters-settings:
  mnd:
    ignored-numbers: 0o400,0o600,0o660,0o640,0o644,0o700,0o750
    ignored-functions: os.WriteFile,os.MkdirAll

issues:
  fix: true
